### PR TITLE
fix tracking when module used multiple times

### PR DESCRIPTION
**Pull request by jhrmnn**

### CODE REVIEW

**Comment by sfetzel** [comment]
This fix can cause memory problems because `self._activations` and `self._sensitivities` are never cleared and will fill up with all the input data. Or did I miss something?

The values of these variables could be cleared in the `update_cov` function. What do you think about that?

**Comment by n-gao** [comment]
Thanks for getting back on this. I completely forgot about this PR since I last used this implementation in years ago. There was a reason why I did not accept it. I think you're right @sfetzel. Could you please make a new PR with the correct fix? If done right, I wouldn't do the concatenation here explicitly but create a separate utility to keep track of all activations and sensitivities with a single concatenation at the end (faster). Such a utility should then also be used for the other Fisher blocks.

**Comment by jhrmnn** [comment]
That’s weird. Why would I think that it makes sense to just grow this buffer without any reseting? Feels like some half-finished hack. I of course don’t remember the background :)

**Comment by sfetzel** [comment]
I'm sorry to warm up this topic again but I need this fix for some experiments. How about clearing the activations and sensitivities when calculating the covariance matrix, like so: https://github.com/sfetzel/pytorch-kfac/commit/aa96e34f77f9716e71d7b417d795a32088d6d8b5

**Comment by SamirMoustafa** [comment]
@sfetzel please have a look on this issues as well https://github.com/pytorch/pytorch/issues/46386

**Comment by n-gao** [comment]
@sfetzel please feel free to open a new PR with the implementation idea (or something similar), I suggested. The constant concatenation at each step is also quite inefficient compared to keeping the the tensors in a python list and concatenating only when needed.

**Pull request closed without merging**
